### ISSUE TITLE
The attempted operation is not supported for the type of object referenced.

### ISSUE THREAD

**Issue by lam4o** [microsoft/UwpVpnPluginSample#1]
I am getting "The attempted operation is not supported for the type of object referenced." at channel.Start() in "VpnPlugin.cs"

The only thing I did is to set the VPN IP pointing to the simplevpnserver running on the same machine:
profile.ServerUris.Add(new Uri("http://192.168.1.15")); 

There is connection but it crashes and disconnects immediately:
![image](https://user-images.githubusercontent.com/8136494/150657334-d3e60997-7210-44b7-be86-03cfc5ac4973.png)

**Comment by mitschmi** [comment]
Hi there,
Unfortunately loopback with the sample app and server is not supported. Please try hosting the server on a separate machine.
