### ISSUE TITLE
What to fill into ServerUris property for Windows UWP vpn profile

### ISSUE THREAD

**Issue by woodandfire** [microsoft/UwpVpnPluginSample#2]
n CreateAppProfile() part function as bellow.

// Hard coding parameters for the profile
            VpnPlugInProfile profile = new VpnPlugInProfile();
            ...

            **profile.ServerUris.Add(new Uri("http://10.137.192.135"));**
            var returnedStatus = await agent.AddProfileFromObjectAsync(profile);
            ...

I don't kown what url to fill into "ServerUris" property, and what content should be provide in that url.

And :

var connectStatus = await agent.ConnectProfileAsync(pluginProfile);

the connectStatus always return Other or CannotFindProfile.

**Comment by mediaexplorer74** [comment]
> n CreateAppProfile() part function as bellow.
> 
> // Hard coding parameters for the profile VpnPlugInProfile profile = new VpnPlugInProfile(); ...
> 
> ```
>         **profile.ServerUris.Add(new Uri("http://10.137.192.135"));**
>         var returnedStatus = await agent.AddProfileFromObjectAsync(profile);
>         ...
> ```
> 
> I don't kown what url to fill into "ServerUris" property, and what content should be provide in that url.
> 
> And :
> 
> var connectStatus = await agent.ConnectProfileAsync(pluginProfile);
> 
> the connectStatus always return Other or CannotFindProfile.

Hi! Are you trying to create your own UWP VPN client? Cool! Good luck! =) I dream about free VPN client for my old sweet Lumia 950 winphone ))

**Comment by mitschmi** [comment]
The server URI should refer to whatever VPN server you are trying to connect to. There is a sample server that handles basic nonencrypted UDP traffic. 
You could also search online for other open source VPN servers to connect to/set-up. Note that in order to connect to said servers, you would most likely need to change the Encapsulate/Decapsulate logic for whatever protocol your VPN server uses.

**Comment by bwjohns4** [comment]
@woodandfire , did you ever get this to work? I am having the same issue that no matter what I put in the server uri, it gives an exception that `WinRT originate error - 0x80070057 : 'vpn.mydomain.com is not a valid absolute URI.'.`. What uri can I hardcode to get this to work? I actually hardcoded it as "https://mydomain.com". 

Then it also returns 1 which translates to "Other" on the error enum just like the original issue posted here:

var connectStatus = await agent.ConnectProfileAsync(pluginProfile);
the connectStatus always return Other or CannotFindProfile.
